import urllib.request, json, time

tests = [
    ("TVC", "Thiruvananthapuram railway station Kerala"),
    ("VAK", "Varkala railway station Kerala"),
    ("QLN", "Kollam railway station Kerala"),
    ("KYJ", "Kayamkulam railway station Kerala"),
    ("MVLK", "Mavelikkara railway station Kerala"),
    ("CNGR", "Chengannur railway station Kerala"),
    ("TRVL", "Thiruvalla railway station Kerala"),
    ("CGY", "Changanassery railway station Kerala"),
    ("KTYM", "Kottayam railway station Kerala"),
    ("ERN", "Ernakulam Town railway station Kerala"),
    ("TCR", "Thrissur railway station Kerala"),
    ("PGT", "Palakkad railway station Kerala"),
    ("CBE", "Coimbatore railway station Tamil Nadu"),
    ("TUP", "Tiruppur railway station Tamil Nadu"),
    ("ED", "Erode railway station Tamil Nadu"),
    ("SA", "Salem railway station Tamil Nadu"),
    ("JTJ", "Jolarpet railway station Tamil Nadu"),
    ("VN", "Vaniyambadi railway station Tamil Nadu"),
    ("KPD", "Katpadi railway station Tamil Nadu"),
    ("AJJ", "Arakkonam railway station Tamil Nadu"),
    ("PER", "Perambur railway station Tamil Nadu"),
    ("MAS", "Chennai Central railway station Tamil Nadu"),
    ("ADI", "Ahmedabad railway station Gujarat"),
    ("ND", "Nadiad railway station Gujarat"),
    ("ANND", "Anand railway station Gujarat"),
    ("BRC", "Vadodara railway station Gujarat"),
    ("ST", "Surat railway station Gujarat"),
    ("VAPI", "Vapi railway station Gujarat"),
    ("BOR", "Boisar railway station Maharashtra"),
    ("BSR", "Vasai Road railway station Maharashtra"),
    ("KYN", "Kalyan railway station Maharashtra"),
    ("PUNE", "Pune railway station Maharashtra"),
    ("SUR", "Solapur railway station Maharashtra"),
    ("KLBG", "Kalaburagi railway station Karnataka"),
    ("WADI", "Wadi railway station Karnataka"),
    ("YG", "Yadgir railway station Karnataka"),
    ("RC", "Raichur railway station Karnataka"),
    ("MALM", "Mantralayam Road railway station Andhra Pradesh"),
    ("AD", "Adoni railway station Andhra Pradesh"),
    ("GTL", "Guntakal railway station Andhra Pradesh"),
    ("GY", "Gooty railway station Andhra Pradesh"),
    ("TU", "Tadipatri railway station Andhra Pradesh"),
    ("YA", "Yerraguntla railway station Andhra Pradesh"),
    ("HX", "Cuddapah railway station Andhra Pradesh"),
    ("RU", "Renigunta railway station Andhra Pradesh"),
    ("NDLS", "New Delhi railway station Delhi"),
    ("HWH", "Howrah railway station West Bengal"),
    ("SBC", "KSR Bengaluru City railway station Karnataka"),
    ("CSTM", "Chhatrapati Shivaji Terminus Mumbai Maharashtra"),
    ("NGP", "Nagpur railway station Maharashtra"),
    ("LKO", "Lucknow railway station Uttar Pradesh"),
    ("GWL", "Gwalior railway station Madhya Pradesh"),
    ("AGC", "Agra Cantt railway station Uttar Pradesh"),
    ("JP", "Jaipur railway station Rajasthan"),
    ("AII", "Ajmer railway station Rajasthan"),
    ("UDZ", "Udaipur City railway station Rajasthan"),
    ("CDG", "Chandigarh railway station Punjab"),
    ("ASR", "Amritsar railway station Punjab"),
    ("LDH", "Ludhiana railway station Punjab"),
    ("AMV", "Ahmedabad railway station Gujarat"),
    ("RTM", "Ratlam railway station Madhya Pradesh"),
    ("MMCT", "Mumbai Central railway station Maharashtra"),
    ("DR", "Mumbai Dadar railway station Maharashtra"),
    ("TNA", "Thane railway station Maharashtra"),
    ("LTT", "Mumbai Lokmanya Tilak Terminus Maharashtra"),
    ("MYS", "Mysuru railway station Karnataka"),
    ("UBL", "Hubballi railway station Karnataka"),
    ("GNT", "Guntur railway station Andhra Pradesh"),
    ("BZA", "Vijayawada railway station Andhra Pradesh"),
    ("SC", "Secunderabad railway station Telangana"),
    ("HYB", "Hyderabad Deccan railway station Telangana"),
    ("MDN", "Miryalaguda railway station Telangana"),
    ("NZB", "Nizamabad railway station Telangana"),
    ("WL", "Warangal railway station Telangana"),
    ("GNT", "Guntur railway station Andhra Pradesh"),
    ("VSKP", "Visakhapatnam railway station Andhra Pradesh"),
    ("VZM", "Vizianagaram railway station Andhra Pradesh"),
    ("PSA", "Palasa railway station Andhra Pradesh"),
    ("VBL", "Vijayawada railway station Andhra Pradesh"),
    ("TBM", "Tambaram railway station Tamil Nadu"),
    ("MS", "Chennai Egmore railway station Tamil Nadu"),
    ("TPJ", "Tiruchirappalli railway station Tamil Nadu"),
    ("MDU", "Madurai railway station Tamil Nadu"),
    ("NCJ", "Nagercoil railway station Tamil Nadu"),
    ("TVC", "Thiruvananthapuram railway station Kerala"),
    ("CLT", "Kozhikode railway station Kerala"),
    ("CAN", "Kannur railway station Kerala"),
    ("ALLP", "Alappuzha railway station Kerala"),
    ("ERS", "Ernakulam Junction railway station Kerala"),
    ("JAT", "Jammu Tawi railway station Jammu Kashmir"),
    ("LJN", "Lucknow Junction railway station Uttar Pradesh"),
    ("MB", "Moradabad railway station Uttar Pradesh"),
    ("BE", "Bareilly railway station Uttar Pradesh"),
    ("KGM", "Kathgodam railway station Uttarakhand"),
    ("DDN", "Dehradun railway station Uttarakhand"),
    ("HW", "Haridwar railway station Uttarakhand"),
    ("CNB", "Kanpur Central railway station Uttar Pradesh"),
    ("ALD", "Prayagraj railway station Uttar Pradesh"),
    ("BSB", "Varanasi railway station Uttar Pradesh"),
    ("MGS", "Mughal Sarai railway station Uttar Pradesh"),
    ("PNBE", "Patna railway station Bihar"),
    ("GAYA", "Gaya railway station Bihar"),
    ("DHN", "Dhanbad railway station Jharkhand"),
    ("TATA", "Tatanagar railway station Jharkhand"),
    ("RNC", "Ranchi railway station Jharkhand"),
    ("BBS", "Bhubaneswar railway station Odisha"),
    ("CTC", "Cuttack railway station Odisha"),
    ("VSKP", "Visakhapatnam railway station Andhra Pradesh"),
    ("GNT", "Guntur railway station Andhra Pradesh"),
    ("GTL", "Guntakal railway station Andhra Pradesh"),
]

for code, q in tests:
    url = "https://nominatim.openstreetmap.org/search?q=" + urllib.request.quote(q) + "&countrycodes=in&format=json&limit=1"
    req = urllib.request.Request(url, headers={"User-Agent": "RailwayProject/1.0"})
    try:
        resp = urllib.request.urlopen(req, timeout=5)
        data = json.loads(resp.read().decode())
        if data:
            lon = float(data[0]["lon"])
            lat = float(data[0]["lat"])
            print(code + ": [" + str(round(lon,5)) + ", " + str(round(lat,5)) + "],")
        else:
            print(code + ": NOT_FOUND,")
    except Exception as e:
        print(code + ": ERROR_" + str(e)[:30] + ",")
    time.sleep(1.1)  # Respect Nominatim rate limit of 1 req/sec
